apps/login/urls.py
from django.urls import path
from apps.login import views

app_name = 'login'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
]

django_login_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls', namespace='login')),
    path('captcha/', include('captcha.urls'))
]

apps/login/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class CreateUpdateModelMixin(models.Model):
    create_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        abstract = True


class User(CreateUpdateModelMixin, models.Model):
    gender = (
        ('male', '男'),
        ('female', '女')
    )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=10, choices=gender,
                           default='male')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['create_time']
        verbose_name = 'user'
        verbose_name_plural = verbose_name

apps/login/forms.py
from captcha.fields import CaptchaField
from django import forms

from apps.login.models import User


class UserForm(forms.Form):
    username = forms.CharField(label='用户', max_length=128,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control'}
                               ))
    password = forms.CharField(label='密码', max_length=256,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control'}
                               ))

    captcha = CaptchaField(label='验证码')


class RegisterForm(forms.Form):
    gender = (
        ('male', '男'),
        ('female', '女')
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')

    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data['password1']
        password2 = cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('输入密码不匹配')

        return cleaned_data

apps/login/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import View
from apps.login.models import User
from apps.login.forms import UserForm, RegisterForm


def index(request):
    pass
    return render(request, 'login/index.html')


class LoginView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.session.get('is_login'):
            return redirect(reverse('login:index'))
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = UserForm()
        return render(request, 'login/login.html', {
            'form': form
        })

    def post(self, request):
        form = UserForm(data=request.POST)
        message = '请填写内容！'

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try:
                user = User.objects.get(name=username)
                if user.password == password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect(reverse('login:index'))
                else:
                    message = '登录失败'
            except User.DoesNotExist:
                message = '用户不存在'

        return render(request, 'login/login.html', {
            'message': message,
            'form': form
        })

# def login(request):
#     if request.session.get('is_login'):
#         return redirect(reverse('login:index'))
#
#     if request.method == 'POST':
#         form = UserForm(data=request.POST)
#         message = '请填写内容！'
#
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             try:
#                 user = User.objects.get(name=username)
#                 if user.password == password:
#                     request.session['is_login'] = True
#                     request.session['user_id'] = user.id
#                     request.session['user_name'] = user.name
#                     return redirect(reverse('login:index'))
#                 else:
#                     message = '登录失败'
#             except User.DoesNotExist:
#                 message = '用户不存在'
#
#         return render(request, 'login/login.html', {
#             'message': message,
#             'form': form
#         })
#     form = UserForm()
#     return render(request, 'login/login.html', {
#         'form': form
#     })


class RegisterView(View):

    def dispatch(self, request, *args, **kwargs):
        if request.session.get('is_login'):
            return redirect(reverse('login:index'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = RegisterForm()
        return render(request, 'login/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        message = '请填写内容'
        if form.is_valid():
            username = form.cleaned_data['username']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            sex = form.cleaned_data['sex']

            if User.objects.filter(name=username):
                message = '用户已经存在，请重新选择用户名！'
                return render(request, 'login/register.html', locals())

            if User.objects.filter(email=email):  # 邮箱地址唯一
                message = '该邮箱地址已被注册，请使用别的邮箱！'
                return render(request, 'login/register.html', locals())

            User.objects.create(
                name=username,
                password=password2,
                email=email,
                sex=sex
            )
            return redirect(reverse('login:login'))

# def register(request):
#     if request.session.get('is_login'):
#         return redirect(reverse('login:index'))
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         message = '请填写内容'
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password2 = form.cleaned_data['password2']
#             email = form.cleaned_data['email']
#             sex = form.cleaned_data['sex']
#
#             if User.objects.filter(name=username):
#                 message = '用户已经存在，请重新选择用户名！'
#                 return render(request, 'login/register.html', locals())
#
#             if User.objects.filter(email=email):  # 邮箱地址唯一
#                 message = '该邮箱地址已被注册，请使用别的邮箱！'
#                 return render(request, 'login/register.html', locals())
#
#             User.objects.create(
#                 name=username,
#                 password=password2,
#                 email=email,
#                 sex=sex
#             )
#             return redirect(reverse('login:login'))
#
#     form = RegisterForm()
#     return render(request, 'login/register.html', locals())


def logout(request):
    if not request.session.get('is_login'):
        return redirect(reverse('login:index'))
    request.session.flush()
    return redirect(reverse('login:index'))

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    {% block css %}
    
    {% endblock %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Django</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="nav navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'login:index' %}">Home <span class="sr-only">(current)</span></a>
        </div>
        <div class="nav navbar-nav navbar-right">
            {% if request.session.is_login %}
            <a class="nav-item nav-link" href="#">{{ request.session.user_name }}</a>
            <a class="nav-item nav-link" href="{% url 'login:logout' %}">注销</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login:login' %}">登录</a>
            <a class="nav-item nav-link" href="{% url 'login:register' %}">注册</a>
            {% endif %}
        </div>
      </div>
    </nav>

    <br>

    {% block content %}{% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

templates/login/index.html
{% extends 'base.html' %}

{% block content %}
    {% if request.session.is_login %}
    <h1>hello {{ request.session.user_name }}</h1>
    {% else %}
    <h1>请登录</h1>
    {% endif %}
{% endblock %}

templates/login/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-md-4 col-md-offset-8">
      <form class='form-login' action="{% url 'login:login' %}" method="post">
              {% if message %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
          <h2 class="text-center">欢迎登录</h2>

          <div class="form-group">
              {{ form.username.label_tag }}
              {{ form.username }}
          </div>

          <div class="form-group">
              {{ form.password.label_tag }}
              {{ form.password }}
          </div>

          <div class="form-group">
              {{ form.captcha.errors }}
              {{ form.captcha.label_tag }}
              {{ form.captcha }}
          </div>

{#          <div class="form-group">#}
{#            <label for="id_username">用户名：</label>#}
{#            <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="id_password">密码：</label>#}
{#            <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>#}
{#          </div>#}

          {% csrf_token %}
          <button type="reset" class="btn btn-default pull-left">重置</button>
          <button type="submit" class="btn btn-primary pull-right">提交</button>
      </form>
    </div>
</div> <!-- /container -->

{% endblock %}

templates/login/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="{% url 'login:register' %}" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}

              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                  {{ form.username.label_tag }}
                  {{ form.username}}
              </div>
              <div class="form-group">
                  {{ form.password1.label_tag }}
                  {{ form.password1 }}
              </div>
              <div class="form-group">
                  {{ form.password2.label_tag }}
                  {{ form.password2 }}
              </div>
              <div class="form-group">
                  {{ form.email.label_tag }}
                  {{ form.email }}
              </div>
              <div class="form-group">
                  {{ form.sex.label_tag }}
                  {{ form.sex }}
              </div>
              <div class="form-group">
                  {{ form.captcha.errors }}
                  {{ form.captcha.label_tag }}
                  {{ form.captcha }}
              </div>

              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>

          </form>
        </div>
    </div>
{% endblock %}